version: "3"
services:
  db:
    container_name: mysql
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yoo
      MYSQL_DATABASE: app_db
      MYSQL_USER: gosman
      MYSQL_PASSWORD: yoo
    volumes:
      - ./dbdata:/var/lib/mysql